---
- import_playbook: 2_validate_system.yml
- import_playbook: 3_install_packages.yml
- import_playbook: 4_install_spack.yml
- import_playbook: 5_setup_mig.yml
- import_playbook: 6_create_mig_instances.yml
- import_playbook: 7_setup_users.yml  
- import_playbook: 8_setup_permissions.yml
- import_playbook: 9_install_cuda.yml 
- import_playbook: 10_password_login.yml 
